---
- hosts: dev
  become: True
  tasks:
     - name: Install prerequisites
       apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

     - name: instal requir packages.
       apt: name={{ item }} update_cache=yes state=latest
       loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

     - name: add gpt key
       apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

     - name: add docker repository to apt
       apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

     - name: install docker
       apt: name={{ item }} update_cache=yes state=latest
       loop: [ docker-ce, docker-ce-cli, containerd.io ]
     
     - name: Install Docker Module for Python
       pip:
          name: docker 
     
     - name: Start the container
       docker_container:
         name: nikhil
         image: "nikhilnambiars/tomcat:{{DOCKER_TAG}}"
         state: started
         published_ports:
          - 0.0.0.0:8081:8080
